/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Counter: typeof import('./src/components/Counter.vue')['default']
    ElBadge: typeof import('element-ui/lib/badge')['default']
    ElButton: typeof import('element-ui/lib/button')['default']
    ElCascader: typeof import('element-ui/lib/cascader')['default']
    ElCheckbox: typeof import('element-ui/lib/checkbox')['default']
    ElCheckboxGroup: typeof import('element-ui/lib/checkbox-group')['default']
    ElCol: typeof import('element-ui/lib/col')['default']
    ElColorPicker: typeof import('element-ui/lib/color-picker')['default']
    ElDatePicker: typeof import('element-ui/lib/date-picker')['default']
    ElDialog: typeof import('element-ui/lib/dialog')['default']
    ElDrawer: typeof import('element-ui/lib/drawer')['default']
    ElDropdown: typeof import('element-ui/lib/dropdown')['default']
    ElDropdownItem: typeof import('element-ui/lib/dropdown-item')['default']
    ElDropdownMenu: typeof import('element-ui/lib/dropdown-menu')['default']
    ElForm: typeof import('element-ui/lib/form')['default']
    ElFormItem: typeof import('element-ui/lib/form-item')['default']
    ElInput: typeof import('element-ui/lib/input')['default']
    ElInputNumber: typeof import('element-ui/lib/input-number')['default']
    ElLink: typeof import('element-ui/lib/link')['default']
    ElMenu: typeof import('element-ui/lib/menu')['default']
    ElMenuItem: typeof import('element-ui/lib/menu-item')['default']
    ElOption: typeof import('element-ui/lib/option')['default']
    ElPagination: typeof import('element-ui/lib/pagination')['default']
    ElPopconfirm: typeof import('element-ui/lib/popconfirm')['default']
    ElPopover: typeof import('element-ui/lib/popover')['default']
    ElRadio: typeof import('element-ui/lib/radio')['default']
    ElRadioGroup: typeof import('element-ui/lib/radio-group')['default']
    ElSelect: typeof import('element-ui/lib/select')['default']
    ElSlider: typeof import('element-ui/lib/slider')['default']
    ElSubmenu: typeof import('element-ui/lib/submenu')['default']
    ElSwitch: typeof import('element-ui/lib/switch')['default']
    ElTable: typeof import('element-ui/lib/table')['default']
    ElTableColumn: typeof import('element-ui/lib/table-column')['default']
    ElTabPane: typeof import('element-ui/lib/tab-pane')['default']
    ElTabs: typeof import('element-ui/lib/tabs')['default']
    ElTag: typeof import('element-ui/lib/tag')['default']
    ElTimePicker: typeof import('element-ui/lib/time-picker')['default']
    ElTooltip: typeof import('element-ui/lib/tooltip')['default']
    ElTransfer: typeof import('element-ui/lib/transfer')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
