/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Counter: typeof import('./src/components/Counter.vue')['default']
    ElButton: typeof import('element-ui/lib/button')['default']
    ElCheckbox: typeof import('element-ui/lib/checkbox')['default']
    ElCheckboxGroup: typeof import('element-ui/lib/checkbox-group')['default']
    ElCol: typeof import('element-ui/lib/col')['default']
    ElDatePicker: typeof import('element-ui/lib/date-picker')['default']
    ElForm: typeof import('element-ui/lib/form')['default']
    ElFormItem: typeof import('element-ui/lib/form-item')['default']
    ElInput: typeof import('element-ui/lib/input')['default']
    ElMenu: typeof import('element-ui/lib/menu')['default']
    ElMenuItem: typeof import('element-ui/lib/menu-item')['default']
    ElOption: typeof import('element-ui/lib/option')['default']
    ElRadio: typeof import('element-ui/lib/radio')['default']
    ElRadioGroup: typeof import('element-ui/lib/radio-group')['default']
    ElSelect: typeof import('element-ui/lib/select')['default']
    ElSubmenu: typeof import('element-ui/lib/submenu')['default']
    ElSwitch: typeof import('element-ui/lib/switch')['default']
    ElTable: typeof import('element-ui/lib/table')['default']
    ElTableColumn: typeof import('element-ui/lib/table-column')['default']
    ElTimePicker: typeof import('element-ui/lib/time-picker')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
