/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Counter: typeof import('./src/components/Counter.vue')['default']
    ElAside: typeof import('element-ui/lib/aside')['default']
    ElButton: typeof import('element-ui/lib/button')['default']
    ElContainer: typeof import('element-ui/lib/container')['default']
    ElHeader: typeof import('element-ui/lib/header')['default']
    ElMain: typeof import('element-ui/lib/main')['default']
    ElMenu: typeof import('element-ui/lib/menu')['default']
    ElMenuItem: typeof import('element-ui/lib/menu-item')['default']
    ElMenuItemGroup: typeof import('element-ui/lib/menu-item-group')['default']
    ElSubmenu: typeof import('element-ui/lib/submenu')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
